viaa:
    logging:
        level: DEBUG
app:
    environment: !ENV ${APP_ENVIRONMENT}
    rabbitmq:
        user: !ENV ${RABBIT_MQ_USER}
        passwd: !ENV ${RABBIT_MQ_PASSWD}
        host: !ENV ${RABBIT_MQ_HOST}
        port: !ENV ${RABBIT_MQ_PORT}
        incoming:
            queue: !ENV ${S3_EVENTS_QUEUE}
            exchange: !ENV ${S3_EVENTS_EXCHANGE}
        outgoing:
            queue: !ENV ${FILETRANSFER_QUEUE}
            exchange: !ENV ${FILETRANSFER_EXCHANGE}
    pid-service:
        host: !ENV ${PID_SERVICE_HOST}
    mediahaven:
        ftp:
            host: !ENV ${MEDIAHAVEN_FTP_HOST}
            user: !ENV ${MEDIAHAVEN_FTP_USER}
            passwd: !ENV ${MEDIAHAVEN_FTP_PASSWD}
    mediahaven-api:
            host: !ENV ${MEDIAHAVEN_API_HOST}
            user: !ENV ${MEDIAHAVEN_API_USER}
            passwd: !ENV ${MEDIAHAVEN_API_PASSWD}
    organisations-api:
        host: !ENV ${ORGANISATIONS_API_HOST}